'use client'
import {useEffect,useRef,useState} from 'react'
import ModuleShell from '@/components/ModuleShell'
type Hospital={name:string;code:string;logo_url:string|null;sidebar_color:string;accent_color:string;background_color:string}
const W=320,H=120
export default function HospitalProfilePage(){
 const[h,setH]=useState<Hospital|null>(null),[msg,setMsg]=useState(''),[src,setSrc]=useState(''),[zoom,setZoom]=useState(100),[x,setX]=useState(50),[y,setY]=useState(50);const imgRef=useRef<HTMLImageElement>(null)
 useEffect(()=>{fetch('/api/admin/hospital-profile',{cache:'no-store'}).then(async r=>{if(r.ok){const z=(await r.json()).hospital;setH(z);setSrc(z.logo_url||'')}})},[])
 function pick(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)){setMsg('Use PNG, JPG or WebP.');return}if(f.size>5*1024*1024){setMsg('Logo file must be 5 MB or smaller.');return}const rd=new FileReader();rd.onload=()=>{setSrc(String(rd.result));setZoom(100);setX(50);setY(50);setMsg('')};rd.readAsDataURL(f)}
 function normalizedLogo(){if(!src)return '';const im=imgRef.current;if(!im||!im.naturalWidth)return src;const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');if(!ctx)return src;const contain=Math.min(W/im.naturalWidth,H/im.naturalHeight);const scale=contain*(zoom/100);const dw=im.naturalWidth*scale,dh=im.naturalHeight*scale;const dx=(W-dw)*(x/100),dy=(H-dh)*(y/100);ctx.clearRect(0,0,W,H);ctx.drawImage(im,dx,dy,dw,dh);return c.toDataURL('image/webp',.9)}
 if(!h)return <ModuleShell title="Hospital Profile" eyebrow="ADMIN SETTINGS" description="Manage this hospital's identity and theme."><div className="panel modulePanel">Loading hospital profile…</div></ModuleShell>
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMsg('Saving…');const f=new FormData(e.currentTarget);const body={name:f.get('name'),logoUrl:normalizedLogo(),sidebarColor:f.get('sidebarColor'),accentColor:f.get('accentColor'),backgroundColor:f.get('backgroundColor')};const r=await fetch('/api/admin/hospital-profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const z=await r.json();if(!r.ok){setMsg(z.error||'Unable to save');return}setH(z.hospital);setSrc(z.hospital.logo_url||'');setMsg('Hospital profile saved.');setTimeout(()=>location.reload(),500)}
 return <ModuleShell title="Hospital Profile" eyebrow="ADMIN SETTINGS" description="These settings apply only to users and pages for this hospital."><form className="panel settingsForm" onSubmit={save}><section className="settingsSection"><h3>Hospital identity</h3><label>Hospital name<input className="moduleInput" name="name" defaultValue={h.name} required/></label><label>Hospital code<input className="moduleInput" value={h.code} disabled/></label><div className="logoEditor"><div><b>Hospital logo</b><p>PNG, JPG or WebP · maximum 5 MB · saved at 320 × 120 px.</p><label className="uploadButton">Choose logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={pick}/></label>{src&&<button type="button" className="removeLogo" onClick={()=>setSrc('')}>Remove logo</button>}</div><div className="logoStage">{src?<img ref={imgRef} src={src} alt="Logo preview" style={{width:'100%',height:'100%',objectFit:'contain',transform:`scale(${zoom/100})`,objectPosition:`${x}% ${y}%`}}/>:<span>320 × 120 logo area</span>}</div>{src&&<div className="logoControls"><label>Size <input type="range" min="60" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/><small>{zoom}%</small></label><label>Horizontal position <input type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></label><label>Vertical position <input type="range" min="0" max="100" value={y} onChange={e=>setY(+e.target.value)}/></label></div>}</div></section><section className="settingsSection"><h3>Hospital theme</h3><div className="themeGrid"><label>Left panel color<input name="sidebarColor" type="color" defaultValue={h.sidebar_color}/></label><label>Accent color<input name="accentColor" type="color" defaultValue={h.accent_color}/></label><label>Page background<input name="backgroundColor" type="color" defaultValue={h.background_color}/></label></div></section>{msg&&<div className="authMessage">{msg}</div>}<button className="primary">Save hospital profile</button></form></ModuleShell>
}