'use client'
import {useEffect,useState} from 'react'
import ModuleShell from '@/components/ModuleShell'
type Hospital={name:string;code:string;logo_url:string|null;sidebar_color:string;accent_color:string;background_color:string}
export default function HospitalProfilePage(){
 const[h,setH]=useState<Hospital|null>(null),[msg,setMsg]=useState('')
 useEffect(()=>{fetch('/api/admin/hospital-profile',{cache:'no-store'}).then(async r=>{if(r.ok)setH((await r.json()).hospital)})},[])
 if(!h)return <ModuleShell title="Hospital Profile" eyebrow="ADMIN SETTINGS" description="Manage this hospital's identity and theme."><div className="panel modulePanel">Loading hospital profile…</div></ModuleShell>
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={name:f.get('name'),logoUrl:f.get('logoUrl'),sidebarColor:f.get('sidebarColor'),accentColor:f.get('accentColor'),backgroundColor:f.get('backgroundColor')};const r=await fetch('/api/admin/hospital-profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setMsg(x.error||'Unable to save');return}setH(x.hospital);setMsg('Hospital profile saved.');setTimeout(()=>location.reload(),400)}
 return <ModuleShell title="Hospital Profile" eyebrow="ADMIN SETTINGS" description="These settings apply only to users and pages for this hospital."><form className="panel settingsForm" onSubmit={save}><section className="settingsSection"><h3>Hospital identity</h3><label>Hospital name<input className="moduleInput" name="name" defaultValue={h.name} required/></label><label>Hospital code<input className="moduleInput" value={h.code} disabled/></label><label>Logo URL<input className="moduleInput" name="logoUrl" defaultValue={h.logo_url||''} placeholder="https://.../logo.png"/></label>{h.logo_url&&<img className="logoPreview" src={h.logo_url} alt="Hospital logo"/>}</section><section className="settingsSection"><h3>Hospital theme</h3><div className="themeGrid"><label>Left panel color<input name="sidebarColor" type="color" defaultValue={h.sidebar_color}/></label><label>Accent color<input name="accentColor" type="color" defaultValue={h.accent_color}/></label><label>Page background<input name="backgroundColor" type="color" defaultValue={h.background_color}/></label></div></section>{msg&&<div className="authMessage">{msg}</div>}<button className="primary">Save hospital profile</button></form></ModuleShell>
}