'use client'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Activity, Bell, CalendarDays, ChevronRight, ClipboardPlus, FlaskConical, LayoutDashboard, MessageCircle, Search, Stethoscope, Users, WalletCards, X, Send, Clock3, CircleCheck, AlertTriangle } from 'lucide-react'

type Patient={id:string,name:string,uhid:string,age:number,gender:string,mobile:string,doctor:string,time:string,status:string,next:string,nextAt:string,priority?:boolean}
const patients:Patient[]=[
{id:'1',name:'Arjun Kumar',uhid:'HSP-001234',age:48,gender:'Male',mobile:'+91 98765 43210',doctor:'Dr. Raj Sharma',time:'09:00',status:'Vitals done',next:'Doctor consultation',nextAt:'09:25',priority:true},
{id:'2',name:'Priya Singh',uhid:'HSP-001891',age:35,gender:'Female',mobile:'+91 99887 76655',doctor:'Dr. Meera Shah',time:'09:15',status:'Checked in',next:'Vitals / Triage',nextAt:'Now'},
{id:'3',name:'Amit Verma',uhid:'HSP-002104',age:61,gender:'Male',mobile:'+91 91234 55678',doctor:'Dr. Raj Sharma',time:'09:30',status:'Consultation',next:'Lab: CBC + Lipid',nextAt:'10:10'},
{id:'4',name:'Nisha Rao',uhid:'HSP-002311',age:29,gender:'Female',mobile:'+91 93456 78120',doctor:'Dr. K. Rao',time:'09:45',status:'Lab ordered',next:'Sample collection',nextAt:'10:00'}]
const nav=[['Dashboard',LayoutDashboard,'/'],['Patients',Users,'/patients'],['Appointments',CalendarDays,'/appointments'],['Queue',Activity,'/queue'],['Clinical',Stethoscope,'/clinical'],['Laboratory',FlaskConical,'/laboratory'],['Billing',WalletCards,'/billing']] as const
export default function Home(){
 const router=useRouter()
 const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Patient|null>(null); const [toast,setToast]=useState(''); const [activeNav,setActiveNav]=useState('Dashboard'); const [showRegister,setShowRegister]=useState(false); const [notifications,setNotifications]=useState(false); const [automation,setAutomation]=useState(true); const [patientList,setPatientList]=useState(patients)
 function notify(message:string){setToast(message); setTimeout(()=>setToast(''),3500)}
 function registerPatient(event:React.FormEvent<HTMLFormElement>){event.preventDefault(); const form=new FormData(event.currentTarget); const name=String(form.get('name')||'New patient'); const patient:Patient={id:crypto.randomUUID(),name,uhid:`HSP-${String(patientList.length+1235).padStart(6,'0')}`,age:Number(form.get('age')||0),gender:String(form.get('gender')||'Not specified'),mobile:String(form.get('mobile')||''),doctor:'To be assigned',time:'Now',status:'Registered',next:'Vitals / Triage',nextAt:'Now'}; setPatientList(current=>[patient,...current]); setShowRegister(false); notify(`${name} registered successfully`)}
 const shown=useMemo(()=>patientList.filter(p=>(p.name+p.uhid+p.mobile).toLowerCase().includes(query.toLowerCase())),[query,patientList])
 async function send(p:Patient){const message=`Hello ${p.name.split(' ')[0]}, your next step at Aegis Hospital is ${p.next} at ${p.nextAt}. Please follow staff directions. Reply to the hospital if you need assistance.`; try{const r=await fetch('/api/whatsapp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:p.mobile,message})}); if(!r.ok) throw new Error(); setToast(`WhatsApp sent to ${p.name}`)}catch{setToast(`WhatsApp preview ready for ${p.name} — add Cloud API credentials to send`)} setTimeout(()=>setToast(''),3500)}
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="mark">+</div><div><b>AEGIS</b><span>HOSPITAL</span></div></div><div className="tenant">HOSPITAL OPERATIONS</div><nav>{nav.map(([n,I,path])=><button className={activeNav===n?'active':''} key={n} onClick={()=>{setActiveNav(n); router.push(path)}}><I size={18}/><span>{n}</span></button>)}</nav><div className="sidefoot"><span className="pulse"></span><div><b>System operational</b><small>All services online</small></div></div></aside>
  <main><header><div><div className="eyebrow">TUESDAY · 06 OCTOBER 2026</div><h1>Good evening, <strong>Ashish.</strong></h1></div><div className="headerActions"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, UHID, mobile..."/><kbd>⌘ K</kbd></div><button className="icon" aria-label="View notifications" onClick={()=>{setNotifications(!notifications); notify(notifications?'Notifications closed':'You have 4 notifications')}}><Bell size={19}/><i>4</i></button><div className="avatar">AK</div></div></header>
  <section className="content"><div className="sectionHead"><div><span className="overline">LIVE OVERVIEW</span><h2>Patient Flow</h2></div><button className="primary" onClick={()=>setShowRegister(true)}><ClipboardPlus size={17}/> Register Patient</button></div>
  <div className="stats"><article><span>Patients today</span><b>148</b><small className="up">↑ 12% vs yesterday</small></article><article><span>Waiting</span><b>18</b><small>Avg. wait 14 min</small></article><article><span>In consultation</span><b>7</b><small>4 departments</small></article><article className="alert"><span>Needs attention</span><b>6</b><small>Results / follow-ups</small></article></div>
  <div className="grid"><section className="panel queue"><div className="panelHead"><div><h3>Today’s patient queue</h3><p>Live care progression and the next action for each patient.</p></div><button onClick={()=>{setQuery(''); notify('Showing all patients')}}>View all <ChevronRight size={15}/></button></div><div className="tableHead"><span>PATIENT</span><span>DOCTOR / TIME</span><span>CURRENT STATUS</span><span>NEXT STEP</span><span></span></div>{shown.map(p=><div className="row" key={p.id} onClick={()=>setSelected(p)}><div className="patient"><div className="initials">{p.name.split(' ').map(x=>x[0]).join('')}</div><div><b>{p.name}</b><small>{p.uhid} · {p.gender}, {p.age}</small></div></div><div><b>{p.doctor}</b><small>{p.time}</small></div><div><span className="status">{p.status}</span></div><div className="next"><b>{p.next}</b><small><Clock3 size={12}/>{p.nextAt}</small></div><button className="wa" onClick={e=>{e.stopPropagation();send(p)}}><MessageCircle size={16}/> WhatsApp</button></div>)}</section>
  <aside className="panel steps"><div className="panelHead"><div><h3>Next-step monitor</h3><p>Patients requiring coordination.</p></div></div>{patientList.slice(0,3).map((p,i)=><div className="step" key={p.id}><div className={i===0?'stepIcon urgent':'stepIcon'}>{i===0?<AlertTriangle size={16}/>:<CircleCheck size={16}/>}</div><div><b>{p.name}</b><span>{p.next}</span><small>{p.nextAt} · {p.mobile}</small></div><button onClick={()=>send(p)}><Send size={15}/></button></div>)}<div className="rule"></div><div className="auto"><MessageCircle size={19}/><div><b>WhatsApp automation</b><span>Send patient-approved next-step updates and record delivery status.</span></div><button className={automation?'on':'on off'} onClick={()=>{setAutomation(!automation); notify(`WhatsApp automation ${automation?'paused':'enabled'}`)}}>{automation?'ON':'OFF'}</button></div></aside></div>
  </section></main>
  {selected&&<div className="drawer"><button className="close" onClick={()=>setSelected(null)}><X/></button><span className="overline">PATIENT 360 · ACTIVE JOURNEY</span><h2>{selected.name}</h2><p>{selected.uhid} · {selected.gender} · {selected.age} years</p><div className="blood">No critical alerts recorded</div><div className="journey"><div className="done"><i/>Registration <small>08:52</small></div><div className="done"><i/>Check-in <small>09:02</small></div><div className="done"><i/>Vitals <small>09:08</small></div><div className="current"><i/>Current: {selected.status}</div><div><i/>Next: {selected.next} <small>{selected.nextAt}</small></div></div><div className="messageBox"><b>Patient message preview</b><p>Hello {selected.name.split(' ')[0]}, your next step at Aegis Hospital is <strong>{selected.next}</strong> at <strong>{selected.nextAt}</strong>. Please follow staff directions. Reply to the hospital if you need assistance.</p><button className="primary full" onClick={()=>send(selected)}><MessageCircle size={17}/> Send via WhatsApp</button></div></div>}
  {showRegister&&<div className="modalBackdrop" onClick={()=>setShowRegister(false)}><form className="modal" onSubmit={registerPatient} onClick={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setShowRegister(false)}><X/></button><span className="overline">NEW PATIENT</span><h2>Register patient</h2><p>Add a patient to today&apos;s care queue.</p><label>Full name<input name="name" required autoFocus placeholder="Patient name"/></label><div className="formGrid"><label>Age<input name="age" required type="number" min="0" max="130" placeholder="Age"/></label><label>Gender<select name="gender" defaultValue="Female"><option>Female</option><option>Male</option><option>Other</option></select></label></div><label>Mobile<input name="mobile" required placeholder="+91 98765 43210"/></label><button className="primary full" type="submit"><ClipboardPlus size={17}/> Register patient</button></form></div>}
  {toast&&<div className="toast"><CircleCheck size={18}/>{toast}</div>}
 </div>}
