create extension if not exists pgcrypto;
create table if not exists hospitals(id uuid primary key default gen_random_uuid(),hospital_code text unique not null,hospital_name text not null,slug text unique not null,logo_url text,primary_color text default '#8A0303',status text default 'ACTIVE',created_at timestamptz default now());
create table if not exists hospital_users(id uuid primary key references auth.users(id) on delete cascade,hospital_id uuid not null references hospitals(id),role text not null,full_name text,active boolean default true,created_at timestamptz default now());
create table if not exists patients(id uuid primary key default gen_random_uuid(),hospital_id uuid not null references hospitals(id),uhid text not null,first_name text not null,last_name text,mobile text,date_of_birth date,gender text,blood_group text,status text default 'ACTIVE',created_at timestamptz default now(),unique(hospital_id,uhid));
create table if not exists encounters(id uuid primary key default gen_random_uuid(),hospital_id uuid not null references hospitals(id),patient_id uuid not null references patients(id),doctor_id uuid,encounter_type text,encounter_status text,started_at timestamptz,completed_at timestamptz,created_at timestamptz default now());
create table if not exists patient_next_steps(id uuid primary key default gen_random_uuid(),hospital_id uuid not null references hospitals(id),patient_id uuid not null references patients(id),encounter_id uuid references encounters(id),step_type text not null,title text not null,instructions text,due_at timestamptz,status text not null default 'PENDING',assigned_to uuid,created_by uuid references auth.users(id),created_at timestamptz default now(),completed_at timestamptz);
create table if not exists patient_communications(id uuid primary key default gen_random_uuid(),hospital_id uuid not null references hospitals(id),patient_id uuid not null references patients(id),encounter_id uuid references encounters(id),next_step_id uuid references patient_next_steps(id),channel text not null check(channel in('WHATSAPP','SMS','EMAIL','IN_APP')),recipient text not null,message_body text not null,provider_message_id text,delivery_status text default 'QUEUED',sent_by uuid references auth.users(id),sent_at timestamptz,created_at timestamptz default now());
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),hospital_id uuid not null references hospitals(id),user_id uuid references auth.users(id),patient_id uuid references patients(id),encounter_id uuid references encounters(id),action text not null,entity_type text,entity_id uuid,old_value jsonb,new_value jsonb,created_at timestamptz default now());
create index if not exists patients_hospital_uhid_idx on patients(hospital_id,uhid); create index if not exists patients_hospital_mobile_idx on patients(hospital_id,mobile); create index if not exists next_steps_due_idx on patient_next_steps(hospital_id,status,due_at);

alter table hospitals enable row level security; alter table hospital_users enable row level security; alter table patients enable row level security; alter table encounters enable row level security; alter table patient_next_steps enable row level security; alter table patient_communications enable row level security; alter table audit_logs enable row level security;

create or replace function public.current_hospital_id() returns uuid language sql stable security invoker set search_path='' as $$ select hospital_id from public.hospital_users where id=(select auth.uid()) and active=true limit 1 $$;
create policy "tenant hospitals select" on hospitals for select to authenticated using(id=(select public.current_hospital_id()));
create policy "tenant users select" on hospital_users for select to authenticated using(hospital_id=(select public.current_hospital_id()));
create policy "tenant patients select" on patients for select to authenticated using(hospital_id=(select public.current_hospital_id()));
create policy "tenant patients insert" on patients for insert to authenticated with check(hospital_id=(select public.current_hospital_id()));
create policy "tenant patients update" on patients for update to authenticated using(hospital_id=(select public.current_hospital_id())) with check(hospital_id=(select public.current_hospital_id()));
create policy "tenant encounters all" on encounters for all to authenticated using(hospital_id=(select public.current_hospital_id())) with check(hospital_id=(select public.current_hospital_id()));
create policy "tenant next steps all" on patient_next_steps for all to authenticated using(hospital_id=(select public.current_hospital_id())) with check(hospital_id=(select public.current_hospital_id()));
create policy "tenant communications all" on patient_communications for all to authenticated using(hospital_id=(select public.current_hospital_id())) with check(hospital_id=(select public.current_hospital_id()));
create policy "tenant audit select" on audit_logs for select to authenticated using(hospital_id=(select public.current_hospital_id()));

grant select on hospitals,hospital_users to authenticated; grant select,insert,update on patients to authenticated; grant select,insert,update,delete on encounters,patient_next_steps,patient_communications to authenticated; grant select on audit_logs to authenticated;
